projects:
  collect101:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/services/API.service.ts
        docsFilePath: src/graphql
        maxDepth: 3
extensions:
  amplify:
    version: 3
